package: fenics_all
platform: linux-64
engine: python=2
script:
  - conda build -q swig
  - conda build -q fiat
  - conda build -q instant
  - conda build -q ufl
  - conda build -q ffc
  - conda build -q dolfin
